// src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'snail.id';
  linkedinLink = 'https://www.linkedin.com/in/matilda-snail-422823287';
  githubLink = 'https://github.com/JulySnail';
}

<div class="container">
  <div class="left">
    <div class="links">
      <p><a href="{{ linkedinLink }}" class="link">linkedin</a></p>
      <p><a href="{{ githubLink }}" class="link">github</a></p>
    </div>
    <div class="name-container">
      <!-- Text -->
      <p class="name">Matilda Snail</p>
    </div>
    </div>
  <div class="content">
        <!-- Image with rounded corners -->
    <img src="assets\images\IMG_2882.jpeg" alt="Image" class="image">
  </div>
</div>

<router-outlet />

// src/App.jsx
import './App.css'

function App() {
  return (
    <div className="container">
      <div className="left-panel">
        <img src="/profile.jpeg" alt="Matilda Snail" className="profile-photo" />
      </div>
      <div className="right-panel">
        <div className="content">
          <h1 className="name">Matilda Snail</h1>
          <nav className="links">
            <a href="https://www.linkedin.com/in/matilda-snail-422823287" target="_blank" rel="noopener noreferrer">
              LinkedIn
            </a>
            <a href="https://github.com/JulySnail" target="_blank" rel="noopener noreferrer">
              GitHub
            </a>
          </nav>
        </div>
      </div>
    </div>
  )
}

export default App
